default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sourcepost_dev

test:
  <<: *default
  database: sourcepost_test

production:
  <<: *default
  database: sourcepost
  username: sourcepost
  password: <%= ENV['SOURCEPOST_DATABASE_PASSWORD'] %>
